# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate leapfrog model
#'
#' @param demp list of demographic input parameters (TODO: document)
#'
#'
#' @return a list containing projection output arrays
#'
#'  * `totpop1`: Total population by single-age, sex, and year.
#'  * `natdeaths`: Non-AIDS deaths to total population by single-age, sex, and year.
#' 
#' @details
#' The first year of `sx`, `asfr`, `srb`, and `netmig` is not used. This is assumed
#' to apply to the base year population (consistent with Spectrum).
#'
#' @export
#' 
leapfrogR <- function(demp) {
    .Call(`_leapfrog_leapfrogR`, demp)
}

